name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["bug", "fix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "docs", "ci", "refactor", "perf"]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["feature","enhancement","minor"]
  patch:
    labels: ["fix","bug","chore","docs","ci","refactor","perf","patch"]
template: |
  ## Changes
  $CHANGES